# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Layout3_5(object):
    def setupUi(self, Ui_Layout3_5):
        Ui_Layout3_5.setObjectName("Ui_Layout3_5")
        Ui_Layout3_5.resize(800, 600)
        self.scrollArea = QtWidgets.QScrollArea(Ui_Layout3_5)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 800, 550))
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 798, 548))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.l3_5back = QtWidgets.QPushButton(Ui_Layout3_5)
        self.l3_5back.setGeometry(QtCore.QRect(325, 560, 150, 30))
        self.l3_5back.setObjectName("l3_5back")

        self.retranslateUi(Ui_Layout3_5)
        QtCore.QMetaObject.connectSlotsByName(Ui_Layout3_5)

    def retranslateUi(self, Ui_Layout3_5):
        _translate = QtCore.QCoreApplication.translate
        Ui_Layout3_5.setWindowTitle(_translate("Ui_Layout3_5", "Ui_Layout3_5"))
        self.l3_5back.setText(_translate("Ui_Layout3_5", "BACK"))
