# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_layout3(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(800, 600)
        main.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_3 = QtWidgets.QLabel(main)
        self.label_3.setGeometry(QtCore.QRect(365, 130, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.l3capb1 = QtWidgets.QPushButton(main)
        self.l3capb1.setGeometry(QtCore.QRect(350, 440, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l3capb1.setFont(font)
        self.l3capb1.setStyleSheet("color: rgb(0, 0, 0);")
        self.l3capb1.setObjectName("l3capb1")
        self.l3cameralabel = QtWidgets.QLabel(main)
        self.l3cameralabel.setGeometry(QtCore.QRect(275, 170, 250, 250))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.l3cameralabel.setFont(font)
        self.l3cameralabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l3cameralabel.setStyleSheet(" background-color: rgb(150, 150, 150);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.l3cameralabel.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.l3cameralabel.setTextFormat(QtCore.Qt.PlainText)
        self.l3cameralabel.setScaledContents(False)
        self.l3cameralabel.setAlignment(QtCore.Qt.AlignCenter)
        self.l3cameralabel.setWordWrap(True)
        self.l3cameralabel.setObjectName("l3cameralabel")
        self.l4newfileb4 = QtWidgets.QPushButton(main)
        self.l4newfileb4.setGeometry(QtCore.QRect(320, 500, 160, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l4newfileb4.setFont(font)
        self.l4newfileb4.setStyleSheet("color: rgb(0, 0, 0);")
        self.l4newfileb4.setObjectName("l4newfileb4")
        self.L3signoutb4 = QtWidgets.QPushButton(main)
        self.L3signoutb4.setGeometry(QtCore.QRect(700, 10, 80, 30))
        self.L3signoutb4.setStyleSheet("color: rgb(0, 0, 0);")
        self.L3signoutb4.setObjectName("L3signoutb4")
        self.l3_search = QtWidgets.QLineEdit(main)
        self.l3_search.setGeometry(QtCore.QRect(25, 60, 750, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l3_search.setFont(font)
        self.l3_search.setStyleSheet("color: rgb(0, 0, 0);")
        self.l3_search.setClearButtonEnabled(True)
        self.l3_search.setObjectName("l3_search")

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "main"))
        self.label_3.setText(_translate("main", "CAMERA"))
        self.l3capb1.setText(_translate("main", "IMAGE SEARCH"))
        self.l3cameralabel.setToolTip(_translate("main", "CLICK HERE TO OPEN CAMERA AND PRESS SPACE BAR TO CAPTURE, OR \"c\" TO CLOSE"))
        self.l3cameralabel.setText(_translate("main", "CLICK HERE TO OPEN CAMERA AND PRESS SPACE BAR TO CAPTURE, OR \"c\" TO CLOSE"))
        self.l4newfileb4.setText(_translate("main", "CREATE NEW CASE FILE"))
        self.L3signoutb4.setText(_translate("main", "SIGN OUT"))
        self.l3_search.setToolTip(_translate("main", "Search Criminal Name and Hit Enter"))
        self.l3_search.setPlaceholderText(_translate("main", "Search Criminal Name Here"))
